apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: <name-of-resource>
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/laxmankadam123/tekton-cicd-k8s
