apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: < name-of-pipeline-run >
spec:
  pipelineRef:
    name: < name-of-pipelinecreated >
  resources:
    - name: git-source
      resourceRef:
        name: < name-of-pipelineresourcecreated >
  params:
    - name: pathToYamlFile
      value: "src/deploy.yaml"
    - name: imageUrl
      value: < name-of-image >
    - name: imageTag
      value: <tag>
  serviceAccountName: < name-of-servicecreated >
